export type Cesta = {
  slug: string;
  nome: string;
  preco: number;
  imagem: string;
  descricao?: string;
  itens?: string[];
};

export const CESTAS: Cesta[] = [
  {
    slug: 'bambini',
    nome: 'Bambini | Cesta de café da manhã infantil | Congregare',
    preco: 200,
    imagem: 'https://static.wixstatic.com/media/c3a811_d00ea6fc341c4e11b785b4d99839c5f2~mv2.jpeg/v1/fit/w_800,h_800,q_85/file.jpg',
    descricao: 'A partir de R$200,00 Preço promocional',
    itens: [
      '1un. Mini pão de batata',
      '1un. Mini bagel',
      '2un. Waffles',
      '2un. Cream Cheese [Danubio]',
      '1un. Iogurte natural 170g [Leitíssimo]',
      '1un. Potinho de mel silvestre 50g',
      '4un. Macarons artesanais - sabores sortidos',
      '1un. Suco 269ml [Villa Piva] - uva ou tangerina',
      '2un. Frutas frescas (uva verde sem semente + ameixa, pêssego, morango ou mirtilo - conforme disponibilidade )',
      '1un. Creme de avelã 140g [Nutella]',
      '1un. Cachepot em kraft rígido decorado - rosé ou neutro',
      '1un. Envelope com cartão',
      'Fechamento em celofane, fita e tag',
      'TODAS AS CESTAS INCLUEM CARTÃO:',
      'No checkout do pedido você poderá deixar sua mensagem.',
      'Qualquer dúvida, estamos à disposição no botão de WhatsApp!',
      'Confirmação do pedido',
      'Após finalizar o pedido, você receberá uma mensagem da Congregare via WhatsApp.',
      'Vamos confirmar seu pedido e qualquer outro detalhe necessário.',
      'Em caso de pagamento via PIX, informaremos a chave para a transferência.',
      'Horários:',
      'Nossas entregas acontecem aos DOMINGOS das 8h às 12h. De SEGUNDA A SEXTA , das 7h30 às 19h. SÁBADO FECHADO .',
      'Trabalhamos com janelas de 30 minutos. No checkout do pedido você poderá escolher a de sua preferência.',
      'Importante',
      'Se precisarmos fazer uma segunda tentativa de entrega, um novo',
    ],
  },
  {
    slug: 'buongiorno-a-due-cesta-cafe-da-manha-casal',
    nome: 'Buongiorno a Due | Cesta de café da manhã para casal | Congregare',
    preco: 347,
    imagem: 'https://static.wixstatic.com/media/c3a811_6117a5fb6ad24f03b486c17efe0cc140~mv2.jpeg/v1/fit/w_800,h_800,q_85/file.jpg',
    descricao: 'Incluir Mini Buquê? * Selecionar',
    itens: [
      '1un. Requeijão de corte 80g',
      '1un. Lombinho canadense ou Presunto royal 100g - conforme disponibilidade',
      '2un. Ciabatta ou Baguete semi-italiana - conforme disponibilidade',
      '6un. Mini pães de fermentação natural',
      '2un. Frutas frescas (uva verde sem semente + ameixa, pêssego, morango ou mirtilo - conforme disponibilidade)',
      '2un. Granola artesanal 50g cada [Congregare] - adoçada com mel, produção própria',
      '1un. Iogurte natural sem açúcar 170g [Leitíssimo]',
      '1un. Iogurte grego 170g [Delicari]',
      '2un. Manteiga com sal 10g cada [Paysan Breton]',
      '2un. Geleia francesa 28g cada [St. Dalfour]',
      '1un. Potinho de mel 50g',
      '1un. Doce de leite 50g [Rocca]',
      '2un.Macarons artesanais - sabores sortidos',
      '2un. Drip coffee [Orfeu]',
      '2un. Chá [Twinings]',
      '2un. Suco 269ml [Villa Piva] - uva e tangerina',
      '2un. Guardanapos de algodão',
      '1un. Bandeja em madeira reutilizável',
      '1un. Envelope com cartão',
      'Fechamento em celofane, fita e tag',
      'TODAS AS CESTAS INCLUEM CARTÃO:',
      'No checkout do pedido você poderá deixar sua mensagem.',
      'Qualquer dúvida, estamos à disposição no botão de WhatsApp!',
      'Confirmação do pedido',
      'Após finalizar o pedido, você receberá uma mensagem da Congregare via WhatsApp.',
      'Vamos confirmar seu pedido e qualquer outro detalhe necessário. Em caso de pagamento via PIX, informaremos a chave para a transferência.',
      'Horário:',
      'Horários: Nossas entregas acontecem aos DOMINGOS das 8h às 12h. De SEGUNDA A SEXTA, das 7h30 às 19h. SÁBADO FECHADO.',
      'Trabalhamos com janelas de 30 minutos. No checkout do pedido você poderá escolher a de sua preferência.',
      'Importante',
      'Se precisarmos fazer uma segunda tentativa de entrega, um novo',
    ],
  },
  {
    slug: 'buongiorno-surpresa-cesta-de-cafe-da-manha-com-flor',
    nome: 'Cesta de Café da Manhã Com Flores | Congregare',
    preco: 286,
    imagem: 'https://static.wixstatic.com/media/c3a811_0179acb8718c436bbf5b3927a40b45aa~mv2.jpeg/v1/fit/w_800,h_800,q_85/file.jpg',
    descricao: 'A partir de R$286,00 Preço promocional',
    itens: [
      '1un. Requeijão de corte 100g',
      '1un. Caprese (cereja de búfala e tomatinhos no pesto rústico de manjericão com nozes) 100g [Congregare] - produção própria',
      '3un. Mini bagels com gergelim - fermentação natural',
      '3un. Mini pães de batata',
      '1un. Granola artesanal 40g [Congregare] - adoçada com mel, produção própria',
      '1un. Iogurte grego 170g [Delicari]',
      '2un. Manteiga com sal 10g cada [Paysan Breton ou President]',
      '1un. Geleia francesa 28g [St. Dalfour]',
      '1un. Potinho de mel silvestre 50g',
      '1un. Doce de leite 50g [Rocca]',
      '1un. Drip coffee [Orfeu]',
      '1un. Chá [Twinings ou Villa Piva]',
      '1un. Brownie artesanal de chocolate 70g',
      '3un. Macarons artesanais - sabores sortidos',
      '1un. Mini buquê de flores',
      '1un. Caixa redonda em MDF com tampa',
      '1un. Envelope com cartão',
      'Fechamento em celofane, fita e tag',
      'TODAS AS CESTAS INCLUEM CARTÃO:',
      'No checkout do pedido você poderá deixar sua mensagem.',
      'Qualquer dúvida, estamos à disposição no botão de WhatsApp!',
      'Confirmação do pedido',
      'Após finalizar o pedido, você receberá uma mensagem da Congregare via WhatsApp.',
      'Vamos confirmar seu pedido e qualquer outro detalhe necessário.',
      'Em caso de pagamento via PIX, informaremos a chave para a transferência.',
      'Importante',
      'Se precisarmos fazer uma segunda tentativa de entrega, um novo',
    ],
  },
  {
    slug: 'cesta-brunch-congregare',
    nome: 'Cesta de brunch para café da manhã | Congregare',
    preco: 423,
    imagem: 'https://static.wixstatic.com/media/c3a811_a163173c28c549848be81a70c6381dd9~mv2.jpeg/v1/fit/w_800,h_800,q_85/file.jpg',
    descricao: 'Deseja incluir itens adicionais? * Selecionar',
    itens: [
      '1un. Presunto cru italiano 80g [D’or ou Vito Balducci]',
      '1un. Queijo Camembert 125g [Yema ou D’or]',
      '1un. Espumante 200ml [Freixenet]',
      '1un. Suco 269ml [Villa Piva] - tangerina',
      '2un. Mini pães de fermentação natural',
      '1un. Croissant francês [Jules L’Art du Pain]',
      '1un. Geleia francesa 28g [St. Dalfour]',
      '2un. Manteiga com sal 10g cada [Paysan Breton]',
      '1un. Iogurte grego 170g [Delicari]',
      '1un. Granola artesanal 45g [Congregare] - adoçada com mel, produção própria',
      '4un. Macarons artesanais - sabores sortidos',
      '1un. Vasinho com arranjo de flores frescas',
      '1un. Cachepot em kraft rígido decorado - rosé ou neutro',
      '1un. Envelope com cartão',
      'Fechamento em celofane, fita e tag',
      'TODAS AS CESTAS INCLUEM CARTÃO:',
      'No checkout do pedido você poderá deixar sua mensagem.',
      'Qualquer dúvida, estamos à disposição no botão de WhatsApp!',
      'Confirmação do pedido',
      'Após finalizar o pedido, você receberá uma mensagem da Congregare via WhatsApp.',
      'Vamos confirmar seu pedido e qualquer outro detalhe necessário.',
      'Em caso de pagamento via PIX, informaremos a chave para a transferência.',
      'Horários:',
      'Nossas entregas acontecem aos DOMINGOS das 8h às 12h. De SEGUNDA A SEXTA , das 7h30 às 19h. SÁBADO FECHADO .',
      'Trabalhamos com janelas de 30 minutos. No checkout do pedido você poderá escolher a de sua preferência.',
      'Importante',
      'Se precisarmos fazer uma segunda tentativa de entrega, um novo',
    ],
  },
  {
    slug: 'cesta-de-aniversario-auguri',
    nome: 'Cesta de Café da Manhã de Aniversário Auguri | Congregare',
    preco: 289,
    imagem: 'https://static.wixstatic.com/media/c3a811_cf37f773c144479998db3e127bd2a7f6~mv2.jpeg/v1/fit/w_800,h_800,q_85/file.jpg',
    descricao: 'Incluir Flores ou Balão? * Selecionar',
    itens: [
      '1 Doce - Escolha: Mini cake com velinha | Bolinho artesanal & Trios de brigadeiros | Macarons 4un.',
      '1un. Requeijão de corte 80g',
      '1un. Lombinho canadense ou Presunto royal 100g - conforme disponibilidade',
      '2un. Ciabatta ou Baguete semi-italiana - conforme disponibilidade',
      '6un. Mini pães de fermentação natural',
      '2un. Frutas frescas (uva verde sem semente + ameixa, pêssego, morango ou mirtilo - conforme disponibilidade)',
      '1un. Granola artesanal 50g [Congregare] - adoçada com mel, produção própria',
      '1un. Iogurte natural sem açúcar 170g [Leitíssimo]',
      '2un. Manteiga com sal 10g cada [Paysan Breton ou Président]',
      '1un. Geleia francesa 28g [St. Dalfour]',
      '1un. Potinho de mel silvestre 50g ou Doce de leite 50g [Rocca] - escolha',
      '1un. Drip coffee [Orfeu]',
      '1un. Chá [Twinings ou Villa Piva]',
      '1un. Suco 269ml [Villa Piva] - uva ou tangerina',
      '1un. Guardanapo de algodão',
      '1un. Bandeja em madeira reutilizável',
      '1un. Envelope com cartão',
      'Fechamento em celofane, fita e tag',
      'TODAS AS CESTAS INCLUEM CARTÃO:',
      'No checkout do pedido você poderá deixar sua mensagem.',
      'Qualquer dúvida, estamos à disposição no botão de WhatsApp!',
      'Confirmação do pedido',
      'Após finalizar o pedido, você receberá uma mensagem da Congregare via WhatsApp.',
      'Vamos confirmar seu pedido e qualquer outro detalhe necessário. Em caso de pagamento via PIX, informaremos a chave para a transferência.',
      'Horários:',
      'Nossas entregas acontecem aos DOMINGOS das 8h às 12h. De SEGUNDA A SEXTA, das 7h30 às 19h. SÁBADO FECHADO.',
      'Trabalhamos com janelas de 30 minutos. No checkout do pedido você poderá escolher a de sua preferência.',
      'Importante',
      'Se precisarmos fazer uma segunda tentativa de entrega, um novo',
    ],
  },
  {
    slug: 'cesta-de-cafe-da-manha-buongiorno',
    nome: 'Cesta de Café da Manhã Buongiorno | Congregare',
    preco: 265,
    imagem: 'https://static.wixstatic.com/media/c3a811_1e1e2406f18f4c0ebff9f325fc4af4ab~mv2.jpeg/v1/fit/w_800,h_800,q_85/file.jpg',
    descricao: 'Mel ou Doce de Leite? * Selecionar',
    itens: [
      '1un. Requeijão de corte 80g',
      '1un. Lombinho canadense ou Presunto royal 100g - conforme disponibilidade',
      '1un. Ciabatta ou Baguete semi-italiana - conforme disponibilidade',
      '6un. Mini pães de fermentação natural',
      '2un. Frutas frescas (uva verde sem semente + ameixa, pêssego, morango ou mirtilo - conforme disponibilidade )',
      '1un. Granola artesanal 40g cada [Congregare] - adoçada com mel, produção própria',
      '1un. Iogurte natural sem açúcar 170g [Leitíssimo]',
      '2un. Manteiga com sal 10g cada [Paysan Breton ou President]',
      '1un. Geleia francesa 28g cada [St. Dalfour]',
      '1un. Potinho de mel 50g ou Doce de leite 50g [Rocca] - escolha',
      '1un. Drip coffee [Orfeu]',
      '1un. Chá [Twinings ou Villa Piva]',
      '1un. Suco 269ml [Villa Piva] - uva ou tangerina',
      '1un. Guardanapo de algodão',
      '1un. Bandejinha reutilizável de madeira',
      '1un. Envelope com cartão',
      'Fechamento em celofane, fita e tag',
      'TODAS AS CESTAS INCLUEM CARTÃO:',
      'No checkout do pedido você poderá deixar sua mensagem. Qualquer dúvida, estamos à disposição no botão de WhatsApp!',
      'Confirmação do pedido',
      'Após finalizar o pedido, você receberá uma mensagem da Congregare via WhatsApp.',
      'Vamos confirmar seu pedido e qualquer outro detalhe necessário.',
      'Em caso de pagamento via PIX, indique Pagamento Offline no checkout que te informaremos a chave para a transferência.',
      'Vamos confirmar seus dados, calcular a taxa de entrega e informar os dados para pagamento.',
      'Horários:',
      'Horários: Nossas entregas acontecem aos DOMINGOS das 8h às 12h. De SEGUNDA A SEXTA, das 7h30 às 19h. SÁBADO FECHADO.',
      'Trabalhamos com janelas de 30 minutos. No checkout do pedido você poderá escolher a de sua preferência.',
      'Importante',
      'Se precisarmos fazer uma segunda tentativa de entrega, um novo',
    ],
  },
  {
    slug: 'cesta-de-cafe-da-manha-buongiorno-speciale',
    nome: 'Buongiorno Speciale | Cesta de café da manhã | Congregare',
    preco: 472,
    imagem: 'https://static.wixstatic.com/media/c3a811_64c09498babd4fac9058592ed17569b6~mv2.jpeg/v1/fit/w_800,h_800,q_85/file.jpg',
    descricao: 'Buongiorno Speciale | Cesta de café da manhã',
    itens: [
      '1un. Requeijão de corte 80g',
      '1un. Brie ou Camembert 125g',
      '1un. Lombinho canadense ou Presunto royal 100g - conforme disponibilidade',
      '1un. Presunto cru fatiado 100g',
      '2un. Ciabatta ou Baguete semi-italiana - conforme disponibilidade',
      '3un. Mini croissants',
      '6un. Mini pães de fermentação natural',
      '2un. Frutas frescas (uva verde sem semente + ameixa, pêssego, morango ou mirtilo - conforme disponibilidade)',
      '2un. Granola artesanal 40g cada [Congregare] - adoçada com mel, produção própria',
      '1un. Iogurte natural 170g [Leitíssimo]',
      '1un. Iogurte grego 170g [Delicari]',
      '4un. Manteiga com sal 10g cada [Paysan Breton ou Président]',
      '2un. Geleia francesa 28g cada [St. Dalfour]',
      '1un. Potinho de mel silvestre 50g',
      '1un. Doce de leite 50g [Rocca]',
      '1un. Brownie artesanal 90g',
      '1un. Bolo caseiro 65g - (banana com chocolate ou chocolate com mirtilo - conforme disponibilidade',
      '2un. Drip coffee [Orfeu]',
      '2un. Chá [Twinings]',
      '2un. Suco 269ml [Villa Piva] - uva ou tangerina',
      '2un. Guardanapos de algodão',
      '1un. Bandeja em madeira reutilizável',
      '1un. Fechamento em celofane, fita e tag',
      '1un. Envelope com cartão',
      'TODAS AS CESTAS INCLUEM CARTÃO:',
      'No checkout do pedido você poderá deixar sua mensagem.',
      'Qualquer dúvida, estamos à disposição no botão de WhatsApp!',
      'Confirmação do pedido',
      'Após finalizar o pedido, você receberá uma mensagem da Congregare via WhatsApp.',
      'Vamos confirmar seus dados, calcular a taxa de entrega e informar os dados para pagamento.',
      'Horários de entrega',
      'Horários: Nossas entregas acontecem aos DOMINGOS das 8h às 12h. De SEGUNDA A SEXTA, das 7h30 às 19h. SÁBADO FECHADO.',
      'Trabalhamos com janelas de 30 minutos. No checkout do pedido você poderá escolher a de sua preferência.',
      'Importante',
      'Se precisarmos fazer uma segunda tentativa de entrega, um novo',
    ],
  },
  {
    slug: 'cesta-de-cafe-da-manha-de-aniversario',
    nome: 'Buon Compleanno | Cesta de café da manhã de aniversário',
    preco: 385,
    imagem: 'https://static.wixstatic.com/media/c3a811_ec452d0e4b4a4e25b6ab77afdbb7ccdb~mv2.jpeg/v1/fit/w_800,h_800,q_85/file.jpg',
    descricao: 'Deseja incluir itens adicionais? * Selecionar',
    itens: [
      '1 Doce - Escolha: Mini cake com velinha | Brownie & Trios de brigadeiros | Macarons 4un.',
      '1un. Presunto cru 100g',
      '1un. Queijo Camembert 125g',
      '2un. Ciabatta ou Baguete semi-italiana - conforme disponibilidade',
      '6un. Mini pães de fermentação natural',
      '2un. Frutas frescas (uva verde sem semente + ameixa, pêssego, morango ou mirtilo - conforme disponibilidade)',
      '1un. Granola artesanal 50g [Congregare] - adoçada com mel, produção própria',
      '1un. Iogurte natural sem açúcar 170g [Leitíssimo]',
      '2un. Manteiga com sal 10g cada [Paysan Breton]',
      '1un. Geleia francesa 28g [St. Dalfour]',
      '1un. Potinho de mel silvestre 50g',
      '1un. Doce de leite 50g [Rocca]',
      '1un. Drip coffee [Orfeu]',
      '1un. Chá [Twinings]',
      '1un. Suco 269ml [Villa Piva] - uva ou tangerina',
      '1un. Guardanapo de algodão',
      '1un. Cesto em fibra natural',
      '1un. Envelope com cartão',
      'Fechamento em celofane, fita e tag',
      'TODAS AS CESTAS INCLUEM CARTÃO:',
      'No checkout do pedido você poderá deixar sua mensagem.',
      'Qualquer dúvida, estamos à disposição no botão de WhatsApp!',
      'Confirmação do pedido',
      'Após finalizar o pedido, você receberá uma mensagem da Congregare via WhatsApp.',
      'Vamos confirmar seu pedido e qualquer outro detalhe necessário.',
      'Em caso de pagamento via PIX, indique Pagamento Offline no checkout que te informaremos a chave para a transferência.',
      'Horários:',
      'Horários: Nossas entregas acontecem aos DOMINGOS das 8h às 12h. De SEGUNDA A SEXTA, das 7h30 às 19h. SÁBADO FECHADO.',
      'Trabalhamos com janelas de 30 minutos. No checkout do pedido você poderá escolher a de sua preferência.',
      'Importante',
      'Se precisarmos fazer uma segunda tentativa de entrega, um novo',
    ],
  },
  {
    slug: 'mammamia',
    nome: 'Mamma Mia | Cesta Premium de Café da Manhã | Congregare',
    preco: 627,
    imagem: 'https://static.wixstatic.com/media/0d833e_444e6e315d5c46f7bd9b1d794c682c5f~mv2.jpeg/v1/fit/w_800,h_800,q_85/file.jpg',
    descricao: 'Deseja incluir itens adicionais? * Selecionar',
    itens: [
      '1un. Queijo Brie 125g [Île de France ou Paysan Breton]',
      '1un. Queijo Gouda fatiado 100g [D’or]',
      '1un. Salame serrano 80g [Casa Basca]',
      '1un. Presunto cru italiano 100g [D\'or ou Vito Balducci]',
      '1un. Croissant [Jules L’Art du Pain]',
      '2un. Ciabatta ou Baguete semi-italiana - conforme disponibilidade',
      '6un. Mini pães de fermentação natural',
      '1un. Iogurte natural 170g [Leitíssimo]',
      '1un. Iogurte Grego 170g [Delicari]',
      '2un. Granola artesanal 50g [Congregare] - adoçada com mel, produção própria',
      '4un. Manteiga com sal 10g cada [Paysan Breton]',
      '1un. Potinho de mel silvestre 50g',
      '1un. Doce de leite 50g [Rocca]',
      '2un. Geleia francesa 28g [St. Dalfour]',
      '4un. Macarons artesanais',
      '1un. Chocolate Bean to Bar 60g [Mission]',
      '2un. Drip coffee [Orfeu]',
      '2un. Chá [Twinings]',
      '1un. Suco 269ml [Villa Piva]',
      '2un. Frutas frescas (uva verde sem semente + ameixa, pêssego, morango ou mirtilo - conforme disponibilidade)',
      '2un. Guardanapos de algodão',
      '1un. Cesto em fibra natural',
      '1un. Vasinho com flores frescas',
      '1un. Fechamento em celofane, fita e tag',
      '1un. Envelope com cartão',
      'TODAS AS CESTAS INCLUEM CARTÃO:',
      'No checkout do pedido você poderá deixar sua mensagem.',
      'Qualquer dúvida, estamos à disposição no botão de WhatsApp!',
      'Confirmação do pedido',
      'Após finalizar o pedido, você receberá uma mensagem da Congregare via WhatsApp.',
      'Vamos confirmar seu pedido e qualquer outro detalhe necessário. Em caso de pagamento via PIX, informaremos a chave para a transferência.',
      'Horários de entrega',
      'Nossas entregas acontecem de segunda a sexta, das 7h30h às 19h, e aos domingos das 8h30 às 12h. Elas podem ocorrer até 30 minutos antes ou após o horário combinado.',
      'Importante',
      'Se precisarmos fazer uma segunda tentativa de entrega, um novo',
    ],
  },
  {
    slug: 'petit-brunch-cesta-de-cafe-da-manha-com-flores',
    nome: 'Petit Brunch | Cesta de café da manhã com flores | Congregare',
    preco: 286,
    imagem: 'https://static.wixstatic.com/media/c3a811_98aedb15ba6048e59286166fe48e1236~mv2.jpeg/v1/fit/w_800,h_800,q_85/file.jpg',
    descricao: 'A partir de R$286,00 Preço promocional',
    itens: [
      '1un. Mini buquê de flores - Escolha: frescas ou secas',
      '4 un. Mini croissant 30g',
      '2 un. Cream cheese 18g (blister)',
      '2 un. Manteiga 10g [Paysan Breton]',
      '1 un. Geleia francesa de frutas 25g [St. Dalfour]',
      '1 un. Doce de leite 50g [Rocca] - produto artesanal',
      '1 un. Parfait de fruta (iogurte natural, adoçado com mel, mirtilo ou morango, e granola artesanal) - porção individual - produto artesanal',
      '1 un. Granola adoçada apenas com mel 20g [Exclusivo Congregare] - produto artesanal',
      '1 un. Drip coffee [Orfeu]',
      '1 un. Chá inglês [Twinings]',
      '1 un. Suco de uva ou tangerina 269ml (lata)',
      '4 un. Trufa clássica de chocolate - produto artesanal',
      '1 un. Presunto cru fatiado 80g [D’or ou Vito Balducci]',
      '1un. Caixa redonda em MDF com tampa',
      '1un. Envelope com cartão',
      'Fechamento em celofane, fita e tag',
      'TODAS AS CESTAS INCLUEM CARTÃO:',
      'No checkout do pedido você poderá deixar sua mensagem.',
      'Qualquer dúvida, estamos à disposição no botão de WhatsApp!',
      'Confirmação do pedido:',
      'Após finalizar o pedido, você receberá uma mensagem da Congregare via WhatsApp.',
      'Vamos confirmar seu pedido e qualquer outro detalhe necessário.',
      'Em caso de pagamento via PIX, informaremos a chave para a transferência.',
      'Horários:',
      'Nossas entregas acontecem aos DOMINGOS das 8h às 12h. De SEGUNDA A SEXTA , das 7h30 às 19h. SÁBADO FECHADO .',
      'Trabalhamos com janelas de 30 minutos. No checkout do pedido você poderá escolher a de sua preferência.',
      'Importante:',
      'Se precisarmos fazer uma segunda tentativa de entrega, um novo',
    ],
  },
];
